### ISSUE TITLE
教育部重編國語辭典(第五版) 读取崩溃

### ISSUE THREAD

**Issue by terasum** [terasum/medict#637]
```
panic: runtime error: slice bounds out of range [:20361] with capacity 4096

goroutine 85 [running]:
github.com/terasum/medict/internal/gomdict.bigEndianBinToUTF8(...)
	/Users/runner/work/medict/medict/internal/gomdict/util.go:53
github.com/terasum/medict/internal/gomdict.(*MdictBase).decodeKeyBlockInfo(0xc00009d080, {0xc00019c000?, 0x0?, 0x1?})
	/Users/runner/work/medict/medict/internal/gomdict/mdict_base.go:404 +0xb7d
github.com/terasum/medict/internal/gomdict.(*MdictBase).ReadKeyBlockInfo(0xc00009d080)
	/Users/runner/work/medict/medict/internal/gomdict/mdict_base.go:298 +0x9d
github.com/terasum/medict/internal/gomdict.(*Mdict).BuildIndex(0xc000428080)
	/Users/runner/work/medict/medict/internal/gomdict/mdict.go:64 +0x25
github.com/terasum/medict/pkg/service.(*Mdict).BuildIndex(0xc00009cfc0)
	/Users/runner/work/medict/medict/pkg/service/mdict.go:84 +0x8b
github.com/terasum/medict/pkg/apis.(*DictsController).BuildIndexByDictId(0xc00005c588, 0x1001771db?)
	/Users/runner/work/medict/medict/pkg/apis/dicts_handler.go:21 +0x14f
github.com/terasum/medict/pkg/backserver.(*BackServer).DispatchIPCReq(0xc000474d20?, {0xc0002d4b70, 0x12}, 0xc0001e20e0?)
	/Users/runner/work/medict/medict/pkg/backserver/back_server.go:100 +0x66
main.(*App).Dispatch(0xc000474d50, {0xc0002d4b70, 0x12}, 0xc00018cb40)
	/Users/runner/work/medict/medict/app.go:103 +0x125
reflect.Value.call({0x10073ee00?, 0xc000474d50?, 0x10a4b3588?}, {0x10077d01f, 0x4}, {0xc00018cb70, 0x2, 0x0?})
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0x10073ee00?, 0xc000474d50?, 0x30?}, {0xc00018cb70?, 0xc000420028?, 0x100cf8bc8?})
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/reflect/value.go:380 +0xb9
github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call(0xc0001a81c0, {0xc0001e20c0, 0x2, 0x100688380?})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/binding/boundMethod.go:73 +0x20f
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage(0xc0000373c0, {0xc000234280, 0x95}, {0x100cfa0b8, 0xc00058e5a0})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/dispatcher/calls.go:45 +0x188
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage(0x5a59666a53725255?, {0xc000234280?, 0x4149516f6a686f61?}, {0x100cfa0b8?, 0xc00058e5a0?})
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/dispatcher/dispatcher.go:40 +0x56
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processMessage.func1()
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/darwin/frontend.go:321 +0x38
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processMessage in goroutine 37
	/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/darwin/frontend.go:320 +0x1a5
```

**Comment by terasum** [comment]
是UTF16编码的问题，已经修复
